#!/bin/bash

CONFIG=$HOME/.container
CONTAINER=$(cat $CONFIG | grep container | cut -f 2 -d '=')
CONTAINER=$(cat $CONFIG | grep port | cut -f 2 -d '=')

usage() {
	echo "Usage: build_docker [-h] [DOCKER_ARGUMENT ...]"
	echo "Note: before executing, export CONTAINER and PORT varaibles."
}

# help option
[[ $1 == "-h" ]] && usage && exit 0

# handling errors
[ -z "$CONTAINER" ] && echo "error: container name is empty" && exit 1
[ -z "$PORT" ] && echo "error: port number is empty" && exit 2

# handling signals
trap 'clear;echo -e "shutting down container [$CONTAINER:$PORT] please wait..."; docker container stop $(docker ps -q -f ancestor=$CONTAINER;clear)' SIGINT

# building and running container
echo "running container [$CONTAINER:$PORT]..."
docker build . -t $CONTAINER > /dev/null
docker run -p $PORT:$PORT $1 $CONTAINER
