kind: Service
apiVersion: v1
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      targetPort: 5000
  type: LoadBalancer

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          livenessProbe:
           exec:
            command:
            - sh
            - health.sh
           initialDelaySeconds: 25
           periodSeconds: 5
  selector:
    matchLabels:
      app: phpmyadmin
