apiVersion: v1
kind: Pod
metadata:
    name: wordpress
spec:
    containers:
    - image: wordpress
      imagePullPolicy: Never
      name: wordpress
      ports:
      - containerPort: 5050
        protocol: TCP
