apiVersion: v1
kind: Pod
metadata:
    name: phpmyadmin
spec:
    containers:
    - image: phpmyadmin
      imagePullPolicy: Never
      name: phpmyadmin
      livenessProbe:
          exec:
              command:
                  - sh
                  - health.sh
      ports:
      - containerPort: 5000
        protocol: TCP
