apiVersion: v1
kind: Pod
metadata:
    name: wordpress
spec:
    containers:
    - image: wordpress
      name: wordpress
      imagePullPolicy: Never
      ports:
      - containerPort: 5050
        protocol: TCP
      livenessProbe:
          exec:
              command:
                  - sh
                  - health.sh
          initialDelaySeconds: 25
          periodSeconds: 20
